version: "3.7"

networks:

  segrouptwo:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24

services:
  proxy:
    image: nginx:stable
    container_name: "nginx_proxy"
    networks:
      segrouptwo:
        ipv4_address: 172.16.239.2
    ports:
      - "9090:80"
    volumes:
      - $PWD/proxy/nginx.conf:/etc/nginx/nginx.conf
  
  client:
    build: $PWD/sample-client
    container_name: "client"
    networks:
      segrouptwo:
        ipv4_address: 172.16.239.3
    environment:
      NODE_ENV: development
    #ports:
    #  - "8081:3000"
    volumes:
      - $PWD/sample-client/.:/opt/app:rw
    restart: always
  
  backend:
    build: $PWD/api
    container_name: "backend"
    networks:
      segrouptwo:
        ipv4_address: 172.16.239.4
    environment:
      NODE_ENV: development
      #ports:
      #- "8080:3060"
    volumes:
      - $PWD/api/.:/opt/app:rw
    depends_on:
      - mongodb
    restart: always
  
  mongodb:
    image: "mongo:4.0"
    container_name: "mongodb"
    networks:
      segrouptwo:
        ipv4_address: 172.16.239.5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: project
    volumes:
      - $PWD/Database:/data/db
    restart: always

